### PR TITLE
Support dicts for complex types in API calls

### PR DESCRIPTION
**Pull request by logan-stytch**
This PR supports syntax to use basic `dict` types instead of our defined model types in all API calls.

So now, you can do this:
```py
[nav] In [2]: client.users.create(email="noreply@stytch.com", name={"first_name": "Logan", "last_name": "Gore"})
```

**in addition to** using the strongly typed objects:
```py
[nav] In [3]: client.users.create(email="noreply@stytch.com", name=Name(first_name="Logan", last_name="Gore"))
```

All typing has been updated to show that this is possible. As always, though, the values returned by Stytch's API **will be strongly typed**.

### CODE REVIEW

**Comment by kheaps-stytch** [comment]
Do we explicitly need dict, or would a generic Mapping be okay? (See `collections.abc`)

(I also see some usage of List where perhaps a generic Sequence would work, maybe doesn't even to be ordered and a collection would be fine)

On the other hand also possibly a good case for TypedDict rather than Mapping[str, Any] but I think that explicitly requires a dict subclass.

**Comment by kheaps-stytch** [comment]
Also, what will happen if an unexpected key appears in the dictionary? (Or for that matter an unexpected value type, or even an unexpected key type since there's no runtime type check)

**Comment by logan-stytch** [comment]
> Do we explicitly need dict, or would a generic Mapping be okay? (See collections.abc)

We do need a dict since we rely on `item if isinstance(item, dict)` to determine whether we have a dict versus a pydantic model. We could _instead_ rely on something like a Protocol to determine if the object has a `dict()` method, but I'd rather not go that direction.

> (I also see some usage of List where perhaps a generic Sequence would work, maybe doesn't even to be ordered and a collection would be fine)

True, most of these are only that way for easy serialization into the sent JSON.

> Also, what will happen if an unexpected key appears in the dictionary? 

In most cases, the user would get a 400: invalid_argument response. This is being provided as a convenience for the developer, though, in cases where they don't want to import the relevant strongly-typed objects. I personally would always recommend the strong typing approach, but this is an alternative with no typing guarantees.

**Comment by kheaps-stytch** [comment]
> > Do we explicitly need dict, or would a generic Mapping be okay? (See collections.abc)
> 
> We do need a dict since we rely on `item if isinstance(item, dict)` to determine whether we have a dict versus a pydantic model. We could _instead_ rely on something like a Protocol to determine if the object has a `dict()` method, but I'd rather not go that direction.

I think the difference would just be to do an `isinstance(item, Mapping)` ... but also similar to list vs Sequence it might just be better to stick with the well-known types since they may have some downstream impact ex. on JSON serialization

> > (I also see some usage of List where perhaps a generic Sequence would work, maybe doesn't even to be ordered and a collection would be fine)
> 
> True, most of these are only that way for easy serialization into the sent JSON.

As above

> > Also, what will happen if an unexpected key appears in the dictionary?
> 
> In most cases, the user would get a 400: invalid_argument response. This is being provided as a convenience for the developer, though, in cases where they don't want to import the relevant strongly-typed objects. I personally would always recommend the strong typing approach, but this is an alternative with no typing guarantees.

Oh, I <3 strong types too, understand this is for convenience only, glad there's a sane approach to handling.

I'll say from that perspective TypedDict is the best of both worlds -- it's just a dict at runtime, but to type checkers it's so nice -- but I think generating TypedDict definitions would be a separate thing all on its own.

**Review by kheaps-stytch — APPROVED** [review]

**Pull request merged**
